logger:
  disable_existing_loggers: true
  formatters:
    standard:
      format: '%(asctime)s - %(levelname)s - %(name)s - %(filename)s:%(lineno)d: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: standard
      level: DEBUG
    file:
      backupCount: 20
      class: logging.handlers.RotatingFileHandler
      encoding: utf8
      filename: /tmp/piriti.log
      formatter: standard
      level: DEBUG
      maxBytes: 10485760
  loggers:
    piriti:
      handlers:
        - console
      level: DEBUG
      propagate: true
  version: 1